List semesters
scesi/cappuccino-app pull request #29
Opened 2024-08-20 00:18 UTC by gabriel-pantojab

![image](https://github.com/user-attachments/assets/b637ada8-6acb-4fd3-8002-2e03eefa9b64)

2024-09-08 20:57 UTC, MircoPilcoPeralta commented on src/shared/ui/accordion/useAccordionTransition.ts
Faltaría mover el archivo a la carpeta hooks

2024-09-08 20:57 UTC, MircoPilcoPeralta commented on src/shared/ui/accordion/useAccordionTransition.ts
Encontré un bug, al recargar la página, el primer acordeón intenta abrirse automáticamente, pero luego se cierra

2024-09-08 20:57 UTC, MircoPilcoPeralta commented on src/shared/ui/accordion/accordion-summary/accordion-summary.tsx
> +      <button className={styles.accordionSummaryLabel} onClick={toggle}>
Como sugerencia podrías cambiar el nombre del estilo, uno acorde al tag que estas utilizando

2024-09-08 20:57 UTC, MircoPilcoPeralta commented on src/schedule/index.ts
si no se utiliza, seria mejor borrarlo

2024-09-08 20:57 UTC, MircoPilcoPeralta commented on src/schedule/components/subject-accordion/subject-accordion.tsx
> +function SubjectIconExpand() {
Me parece buena idea separar los íconos con sus animaciones,  como sugerencia podrías  separar el ícono del acordeón de semestres también

2024-09-08 21:14 UTC, MircoPilcoPeralta requested changes

2024-09-08 21:14 UTC, MircoPilcoPeralta commented on src/schedule/components/career-details/career-details.tsx
> +    <article className={styles.careerDetails}>
No me parece semánticamente correcto utilizar la etiqueta article para un componente que permite desglozar las materias de una carrera

2024-09-08 21:14 UTC, MircoPilcoPeralta commented on src/schedule/components/semester-accordion/semester-accordion.tsx
> +        expandIcon={
Seria mejor modularizar este componente

2024-09-08 21:14 UTC, MircoPilcoPeralta commented on src/shared/ui/accordion/accordion-context.ts
> +export interface AccordionContextValue {
el nombre de la interfaz da a entender que se trata de un valor, cuando es solo una definición

2024-09-08 21:14 UTC, MircoPilcoPeralta commented on src/shared/ui/accordion/useAccordionTransition.ts
Faltaría mover el archivo a la carpeta hooks

2024-09-08 21:14 UTC, MircoPilcoPeralta commented on src/shared/ui/accordion/useAccordionTransition.ts
Encontré un bug, al recargar la página, el primer acordeón intenta abrirse automáticamente, pero luego se cierra

2024-09-08 21:14 UTC, MircoPilcoPeralta commented on src/shared/ui/accordion/accordion-summary/accordion-summary.tsx
> +      <button className={styles.accordionSummaryLabel} onClick={toggle}>
Como sugerencia podrías cambiar el nombre del estilo, uno acorde al tag que estas utilizando

2024-09-08 21:14 UTC, MircoPilcoPeralta commented on src/schedule/index.ts
si no se utiliza, seria mejor borrarlo

2024-09-08 21:14 UTC, MircoPilcoPeralta commented on src/schedule/components/subject-accordion/subject-accordion.tsx
> +function SubjectIconExpand() {
Me parece buena idea separar los íconos con sus animaciones, como sugerencia podrías separar el ícono del acordeón de semestres también

2024-09-17 01:14 UTC, devferx commented
- Revisión hasta el jueves 19

2024-09-22 22:44 UTC, MircoPilcoPeralta approved these changes, later dismissed

2024-09-24 01:21 UTC, devferx requested changes

2024-09-24 01:21 UTC, devferx commented on src/schedule/components/career-details/career-details.module.css
> +  & .careerDetailsHeader {
Actualizar

2024-09-24 01:21 UTC, devferx commented on src/shared/ui/accordion/accordion-summary/accordion-summary.tsx
> +  const { toggle, expanded } = useContext<AccordionContext>(AccordionContext)
Ponerlo en el mismo archivo solo como interface Props

2024-09-24 01:21 UTC, devferx commented on src/schedule/components/group/group.module.css
> +  background-image: url("data:image/svg+xml,%3csvg viewBox='0 0 16 16' fill='white' xmlns='http://www.w3.org/2000/svg'%3e%3cpath d='M12.207 4.793a1 1 0 010 1.414l-5 5a1 1 0 01-1.414 0l-2-2a1 1 0 011.
Debería ser un asset

2024-09-25 02:42 UTC, devferx approved these changes

2024-09-25 12:42 UTC, MircoPilcoPeralta approved these changes

2024-09-27 01:56 UTC, merged