Feature/delete modal
scesi/cappuccino-app pull request #30
Opened 2024-08-20 02:11 UTC by diegopl653

2024-08-20 02:42 UTC, devferx requested changes

2024-08-20 03:10 UTC, devferx requested changes

2024-08-23 02:47 UTC, devferx requested changes
![image](https://github.com/user-attachments/assets/b27b100c-6f38-438e-8160-9a738bca8ee1)

- Quitar borde del boton de confirmar
- Agregar cursor: pointer para cada boton

2024-09-02 21:57 UTC, devferx requested changes
- Completar los tests de manera satisfactoria

2024-09-06 00:06 UTC, ivancidev requested changes

2024-09-06 00:06 UTC, ivancidev commented on src/shared/ui/delete-modal/delete-modal.tsx
> +          <button className={styles.modalButtonAccept} onClick={handleClose}>
Sería bueno que tengas un componente botón reutilizable

2024-09-06 00:06 UTC, ivancidev commented on src/shared/ui/icons/trash-icon.tsx
![image](https://github.com/user-attachments/assets/d5fdf989-b5a2-4757-becc-39f9a9c9a4a5)
El icono delete lo veo un poco pequeño, en el diseño esta un poco mas grande

2024-09-06 00:06 UTC, ivancidev commented on src/shared/ui/delete-modal/delete-modal.tsx
> +            Cancelar
El texto del boton cancelar esta un poco gris seria bueno que lo pongas negro

2024-09-20 02:52 UTC, diegopl653 commented on src/shared/ui/icons/trash-icon.tsx
Le subi el tamaño

2024-09-20 02:53 UTC, diegopl653 commented on src/shared/ui/delete-modal/delete-modal.tsx
> +            Cancelar
Se modificara en el diseño

2024-09-20 02:53 UTC, diegopl653 commented on src/shared/ui/delete-modal/delete-modal.tsx
> +          <button className={styles.modalButtonAccept} onClick={handleClose}>
Completado

2024-09-21 18:03 UTC, ivancidev requested changes

2024-09-21 18:03 UTC, ivancidev commented on src/shared/ui/Button/button.tsx
Seria bueno llevar a la carpeta interface este codigo 
`interface ButtonProps {
  onClick: () => void
  label: string
  type?: 'button' | 'submit' | 'reset'
  variant: 'cancel' | 'accept'
}`

2024-09-21 18:03 UTC, ivancidev commented on src/shared/ui/delete-modal/delete-modal.tsx
> +  const handleClose = () => {
Seria bueno utilizar como un arrow function en onClick solo cierra la ventana no hara otra cosa: 
`<Button variant="cancel" label="Cancelar" onClick={() => close()} />`

2024-09-21 18:03 UTC, ivancidev commented on src/shared/ui/delete-modal/delete-modal.tsx
> +    <div className={styles.deleteModalContainer} onClick={handleClose} id='modal-container'>
`onClick={() => close()}`

2024-09-24 00:56 UTC, diegopl653 commented on src/shared/ui/Button/button.tsx
no considero que deba ir a interfaces porque solo se usara en este componente

2024-09-24 01:00 UTC, diegopl653 commented on src/shared/ui/delete-modal/delete-modal.tsx
> +    <div className={styles.deleteModalContainer} onClick={handleClose} id='modal-container'>
resuelto

2024-09-24 01:00 UTC, diegopl653 commented on src/shared/ui/delete-modal/delete-modal.tsx
> +  const handleClose = () => {
resuelto

2024-09-24 01:17 UTC, devferx approved these changes

2024-09-26 21:38 UTC, ivancidev approved these changes

2024-09-27 01:53 UTC, merged