Feature/search hook
scesi/cappuccino-app pull request #36
Opened 2024-08-29 22:48 UTC by MircoPilcoPeralta

2024-09-02 22:36 UTC, devferx requested changes
Hacer pruebas unitarias

2024-09-05 05:53 UTC, IVANCCAMA commented on src/utils/deep-searcher.ts
> +const getItemExtractionLevel = <T extends object>(
Cambiar nombre de función a extractItemsAtLevel para mejor entendimiento

2024-09-05 05:55 UTC, IVANCCAMA commented on src/utils/deep-searcher.ts
> +    value = flattenAttributes(value, attribute)
Se puede cambiar nombre de la variable a 'result' para mayor claridad

2024-09-05 05:57 UTC, IVANCCAMA commented on src/utils/deep-searcher.ts
> +  value: T[],
Se puede cambiar nombre a 'items'

2024-09-05 06:02 UTC, IVANCCAMA commented on src/utils/deep-searcher.ts
> +const matchesQueryInHierarchy = <T extends object>(
Agregar tipo de devolución o retorno de la función, al parecer el 'boolena'

2024-09-05 06:04 UTC, IVANCCAMA commented on src/utils/deep-searcher.ts
> +  let value = [item]
Podría renombrarse a 'result'

2024-09-05 06:05 UTC, IVANCCAMA commented on src/utils/deep-searcher.ts
> +  let isValid = false
Renombrar a 'isMatch' de acuerdo al nombre de la funcion

2024-09-05 06:06 UTC, IVANCCAMA commented on src/utils/deep-searcher.ts
> +  values: T[],
Se podría  cambiar el prop a 'items'

2024-09-05 06:09 UTC, IVANCCAMA commented on src/utils/string-comparator.ts
> +    .toString()
Eliminar redundancia .toString() ya que 'fistText' es cadena

2024-09-09 03:04 UTC, MircoPilcoPeralta commented on src/utils/string-comparator.ts
> +    .toString()
Corregido!

2024-09-09 03:09 UTC, MircoPilcoPeralta commented on src/utils/deep-searcher.ts
> +  let value = [item]
no, porque no es el resultado del método

2024-09-10 01:02 UTC, IVANCCAMA submitted a review, later dismissed

2024-09-13 01:14 UTC, devferx requested changes

2024-09-13 01:14 UTC, devferx commented on src/utils/attribute-utils.ts
> +export const flattenAttributes = <T extends object>(
Agregar comentario en la parte superior de que hace este
/*Entrada ->  Salida*/

2024-09-13 01:14 UTC, devferx commented on src/utils/object-level-flattener-utils.ts
> +Method to restructure the objects format inside a list according to an existing property in its hierarchy of composition
Ejemplo

2024-09-17 01:13 UTC, devferx commented
- Fecha límite: Jueves 19
- Revisión hasta 17

2024-09-18 01:29 UTC, devferx requested changes

2024-09-18 01:29 UTC, devferx commented on src/__test__/home/hooks/useSearch.test.ts
> +describe('useSearch hook tests', () => {
Quizas solo este bien con "useSearch hook"

2024-09-18 01:29 UTC, devferx commented on src/home/hooks/useSearch.ts
> +/**
Si es posible poner un ejemplo más corto y resumido

2024-09-18 01:29 UTC, devferx commented on src/utils/string-utils.ts
Quizás podría cambiarse el nombre del archivo, y ponerlo dentro de una carpeta llamada string-utils

2024-09-18 02:15 UTC, IVANCCAMA commented on src/utils/object-level-flattener-utils.ts
> +) => {
La función retorna un arreglo, se puede agregar  T[] quizás

2024-09-19 14:53 UTC, IVANCCAMA submitted a review, later dismissed

2024-10-04 13:36 UTC, devferx approved these changes

2024-10-04 13:36 UTC, merged